version: "3.9"

services:
  fleetdb:
    image: ghcr.io/metal-toolbox/fleetdb:v0.16.6
    depends_on:
      - crdb
      - fleetdb-migrate
    environment:
      - SERVERSERVICE_OIDC_ENABLED=false
      - SERVERSERVICE_CRDB_URI=postgresql://root@crdb:26257/defaultdb?sslmode=disable
      - SERVERSERVICE_DB_ENCRYPTION_DRIVER=base64key://smGbjm71Nxd1Ig5FS0wj9SlbzAIrnolCz9bQQ6uAhl4=
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - hollow

  fleetdb-migrate:
    image: ghcr.io/metal-toolbox/fleetdb:v0.16.6
    command:
      migrate up
    depends_on:
      - crdb
    environment:
      - SERVERSERVICE_CRDB_URI=postgresql://root@crdb:26257/defaultdb?sslmode=disable
    restart: on-failure
    networks:
      - hollow

  crdb:
    image: cockroachdb/cockroach:latest-v21.1
    volumes:
      - db:/cockroach/cockroach-data
    command: start-single-node --insecure
    ports:
        - "8080:8080"
        - "26257:26257"
    restart: unless-stopped
    networks:
      - hollow

volumes:
  db:

networks:
  hollow:
