// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Attributes               string
	ComponentFirmwareVersion string
	ServerComponentTypes     string
	ServerComponents         string
	ServerCredentialTypes    string
	ServerCredentials        string
	Servers                  string
	VersionedAttributes      string
}{
	Attributes:               "attributes",
	ComponentFirmwareVersion: "component_firmware_version",
	ServerComponentTypes:     "server_component_types",
	ServerComponents:         "server_components",
	ServerCredentialTypes:    "server_credential_types",
	ServerCredentials:        "server_credentials",
	Servers:                  "servers",
	VersionedAttributes:      "versioned_attributes",
}
