// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ServerCredential is an object representing the database table.
type ServerCredential struct {
	ID                     string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	ServerID               string    `boil:"server_id" json:"server_id" toml:"server_id" yaml:"server_id"`
	ServerCredentialTypeID string    `boil:"server_credential_type_id" json:"server_credential_type_id" toml:"server_credential_type_id" yaml:"server_credential_type_id"`
	Password               string    `boil:"password" json:"password" toml:"password" yaml:"password"`
	CreatedAt              time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt              time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	Username               string    `boil:"username" json:"username" toml:"username" yaml:"username"`

	R *serverCredentialR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L serverCredentialL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ServerCredentialColumns = struct {
	ID                     string
	ServerID               string
	ServerCredentialTypeID string
	Password               string
	CreatedAt              string
	UpdatedAt              string
	Username               string
}{
	ID:                     "id",
	ServerID:               "server_id",
	ServerCredentialTypeID: "server_credential_type_id",
	Password:               "password",
	CreatedAt:              "created_at",
	UpdatedAt:              "updated_at",
	Username:               "username",
}

var ServerCredentialTableColumns = struct {
	ID                     string
	ServerID               string
	ServerCredentialTypeID string
	Password               string
	CreatedAt              string
	UpdatedAt              string
	Username               string
}{
	ID:                     "server_credentials.id",
	ServerID:               "server_credentials.server_id",
	ServerCredentialTypeID: "server_credentials.server_credential_type_id",
	Password:               "server_credentials.password",
	CreatedAt:              "server_credentials.created_at",
	UpdatedAt:              "server_credentials.updated_at",
	Username:               "server_credentials.username",
}

// Generated where

var ServerCredentialWhere = struct {
	ID                     whereHelperstring
	ServerID               whereHelperstring
	ServerCredentialTypeID whereHelperstring
	Password               whereHelperstring
	CreatedAt              whereHelpertime_Time
	UpdatedAt              whereHelpertime_Time
	Username               whereHelperstring
}{
	ID:                     whereHelperstring{field: "\"server_credentials\".\"id\""},
	ServerID:               whereHelperstring{field: "\"server_credentials\".\"server_id\""},
	ServerCredentialTypeID: whereHelperstring{field: "\"server_credentials\".\"server_credential_type_id\""},
	Password:               whereHelperstring{field: "\"server_credentials\".\"password\""},
	CreatedAt:              whereHelpertime_Time{field: "\"server_credentials\".\"created_at\""},
	UpdatedAt:              whereHelpertime_Time{field: "\"server_credentials\".\"updated_at\""},
	Username:               whereHelperstring{field: "\"server_credentials\".\"username\""},
}

// ServerCredentialRels is where relationship names are stored.
var ServerCredentialRels = struct {
	ServerCredentialType string
	Server               string
}{
	ServerCredentialType: "ServerCredentialType",
	Server:               "Server",
}

// serverCredentialR is where relationships are stored.
type serverCredentialR struct {
	ServerCredentialType *ServerCredentialType `boil:"ServerCredentialType" json:"ServerCredentialType" toml:"ServerCredentialType" yaml:"ServerCredentialType"`
	Server               *Server               `boil:"Server" json:"Server" toml:"Server" yaml:"Server"`
}

// NewStruct creates a new relationship struct
func (*serverCredentialR) NewStruct() *serverCredentialR {
	return &serverCredentialR{}
}

func (r *serverCredentialR) GetServerCredentialType() *ServerCredentialType {
	if r == nil {
		return nil
	}
	return r.ServerCredentialType
}

func (r *serverCredentialR) GetServer() *Server {
	if r == nil {
		return nil
	}
	return r.Server
}

// serverCredentialL is where Load methods for each relationship are stored.
type serverCredentialL struct{}

var (
	serverCredentialAllColumns            = []string{"id", "server_id", "server_credential_type_id", "password", "created_at", "updated_at", "username"}
	serverCredentialColumnsWithoutDefault = []string{"server_id", "server_credential_type_id", "password", "created_at", "updated_at", "username"}
	serverCredentialColumnsWithDefault    = []string{"id"}
	serverCredentialPrimaryKeyColumns     = []string{"id"}
	serverCredentialGeneratedColumns      = []string{}
)

type (
	// ServerCredentialSlice is an alias for a slice of pointers to ServerCredential.
	// This should almost always be used instead of []ServerCredential.
	ServerCredentialSlice []*ServerCredential
	// ServerCredentialHook is the signature for custom ServerCredential hook methods
	ServerCredentialHook func(context.Context, boil.ContextExecutor, *ServerCredential) error

	serverCredentialQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	serverCredentialType                 = reflect.TypeOf(&ServerCredential{})
	serverCredentialMapping              = queries.MakeStructMapping(serverCredentialType)
	serverCredentialPrimaryKeyMapping, _ = queries.BindMapping(serverCredentialType, serverCredentialMapping, serverCredentialPrimaryKeyColumns)
	serverCredentialInsertCacheMut       sync.RWMutex
	serverCredentialInsertCache          = make(map[string]insertCache)
	serverCredentialUpdateCacheMut       sync.RWMutex
	serverCredentialUpdateCache          = make(map[string]updateCache)
	serverCredentialUpsertCacheMut       sync.RWMutex
	serverCredentialUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var serverCredentialAfterSelectHooks []ServerCredentialHook

var serverCredentialBeforeInsertHooks []ServerCredentialHook
var serverCredentialAfterInsertHooks []ServerCredentialHook

var serverCredentialBeforeUpdateHooks []ServerCredentialHook
var serverCredentialAfterUpdateHooks []ServerCredentialHook

var serverCredentialBeforeDeleteHooks []ServerCredentialHook
var serverCredentialAfterDeleteHooks []ServerCredentialHook

var serverCredentialBeforeUpsertHooks []ServerCredentialHook
var serverCredentialAfterUpsertHooks []ServerCredentialHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ServerCredential) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverCredentialAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ServerCredential) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverCredentialBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ServerCredential) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverCredentialAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ServerCredential) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverCredentialBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ServerCredential) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverCredentialAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ServerCredential) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverCredentialBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ServerCredential) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverCredentialAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ServerCredential) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverCredentialBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ServerCredential) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range serverCredentialAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddServerCredentialHook registers your hook function for all future operations.
func AddServerCredentialHook(hookPoint boil.HookPoint, serverCredentialHook ServerCredentialHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		serverCredentialAfterSelectHooks = append(serverCredentialAfterSelectHooks, serverCredentialHook)
	case boil.BeforeInsertHook:
		serverCredentialBeforeInsertHooks = append(serverCredentialBeforeInsertHooks, serverCredentialHook)
	case boil.AfterInsertHook:
		serverCredentialAfterInsertHooks = append(serverCredentialAfterInsertHooks, serverCredentialHook)
	case boil.BeforeUpdateHook:
		serverCredentialBeforeUpdateHooks = append(serverCredentialBeforeUpdateHooks, serverCredentialHook)
	case boil.AfterUpdateHook:
		serverCredentialAfterUpdateHooks = append(serverCredentialAfterUpdateHooks, serverCredentialHook)
	case boil.BeforeDeleteHook:
		serverCredentialBeforeDeleteHooks = append(serverCredentialBeforeDeleteHooks, serverCredentialHook)
	case boil.AfterDeleteHook:
		serverCredentialAfterDeleteHooks = append(serverCredentialAfterDeleteHooks, serverCredentialHook)
	case boil.BeforeUpsertHook:
		serverCredentialBeforeUpsertHooks = append(serverCredentialBeforeUpsertHooks, serverCredentialHook)
	case boil.AfterUpsertHook:
		serverCredentialAfterUpsertHooks = append(serverCredentialAfterUpsertHooks, serverCredentialHook)
	}
}

// One returns a single serverCredential record from the query.
func (q serverCredentialQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ServerCredential, error) {
	o := &ServerCredential{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for server_credentials")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ServerCredential records from the query.
func (q serverCredentialQuery) All(ctx context.Context, exec boil.ContextExecutor) (ServerCredentialSlice, error) {
	var o []*ServerCredential

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ServerCredential slice")
	}

	if len(serverCredentialAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ServerCredential records in the query.
func (q serverCredentialQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count server_credentials rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q serverCredentialQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if server_credentials exists")
	}

	return count > 0, nil
}

// ServerCredentialType pointed to by the foreign key.
func (o *ServerCredential) ServerCredentialType(mods ...qm.QueryMod) serverCredentialTypeQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ServerCredentialTypeID),
	}

	queryMods = append(queryMods, mods...)

	return ServerCredentialTypes(queryMods...)
}

// Server pointed to by the foreign key.
func (o *ServerCredential) Server(mods ...qm.QueryMod) serverQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ServerID),
	}

	queryMods = append(queryMods, mods...)

	return Servers(queryMods...)
}

// LoadServerCredentialType allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (serverCredentialL) LoadServerCredentialType(ctx context.Context, e boil.ContextExecutor, singular bool, maybeServerCredential interface{}, mods queries.Applicator) error {
	var slice []*ServerCredential
	var object *ServerCredential

	if singular {
		var ok bool
		object, ok = maybeServerCredential.(*ServerCredential)
		if !ok {
			object = new(ServerCredential)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeServerCredential)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeServerCredential))
			}
		}
	} else {
		s, ok := maybeServerCredential.(*[]*ServerCredential)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeServerCredential)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeServerCredential))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &serverCredentialR{}
		}
		args = append(args, object.ServerCredentialTypeID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &serverCredentialR{}
			}

			for _, a := range args {
				if a == obj.ServerCredentialTypeID {
					continue Outer
				}
			}

			args = append(args, obj.ServerCredentialTypeID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`server_credential_types`),
		qm.WhereIn(`server_credential_types.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ServerCredentialType")
	}

	var resultSlice []*ServerCredentialType
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ServerCredentialType")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for server_credential_types")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for server_credential_types")
	}

	if len(serverCredentialTypeAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ServerCredentialType = foreign
		if foreign.R == nil {
			foreign.R = &serverCredentialTypeR{}
		}
		foreign.R.ServerCredentials = append(foreign.R.ServerCredentials, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ServerCredentialTypeID == foreign.ID {
				local.R.ServerCredentialType = foreign
				if foreign.R == nil {
					foreign.R = &serverCredentialTypeR{}
				}
				foreign.R.ServerCredentials = append(foreign.R.ServerCredentials, local)
				break
			}
		}
	}

	return nil
}

// LoadServer allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (serverCredentialL) LoadServer(ctx context.Context, e boil.ContextExecutor, singular bool, maybeServerCredential interface{}, mods queries.Applicator) error {
	var slice []*ServerCredential
	var object *ServerCredential

	if singular {
		var ok bool
		object, ok = maybeServerCredential.(*ServerCredential)
		if !ok {
			object = new(ServerCredential)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeServerCredential)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeServerCredential))
			}
		}
	} else {
		s, ok := maybeServerCredential.(*[]*ServerCredential)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeServerCredential)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeServerCredential))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &serverCredentialR{}
		}
		args = append(args, object.ServerID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &serverCredentialR{}
			}

			for _, a := range args {
				if a == obj.ServerID {
					continue Outer
				}
			}

			args = append(args, obj.ServerID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`servers`),
		qm.WhereIn(`servers.id in ?`, args...),
		qmhelper.WhereIsNull(`servers.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Server")
	}

	var resultSlice []*Server
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Server")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for servers")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for servers")
	}

	if len(serverAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Server = foreign
		if foreign.R == nil {
			foreign.R = &serverR{}
		}
		foreign.R.ServerCredentials = append(foreign.R.ServerCredentials, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ServerID == foreign.ID {
				local.R.Server = foreign
				if foreign.R == nil {
					foreign.R = &serverR{}
				}
				foreign.R.ServerCredentials = append(foreign.R.ServerCredentials, local)
				break
			}
		}
	}

	return nil
}

// SetServerCredentialType of the serverCredential to the related item.
// Sets o.R.ServerCredentialType to related.
// Adds o to related.R.ServerCredentials.
func (o *ServerCredential) SetServerCredentialType(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ServerCredentialType) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"server_credentials\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"server_credential_type_id"}),
		strmangle.WhereClause("\"", "\"", 2, serverCredentialPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ServerCredentialTypeID = related.ID
	if o.R == nil {
		o.R = &serverCredentialR{
			ServerCredentialType: related,
		}
	} else {
		o.R.ServerCredentialType = related
	}

	if related.R == nil {
		related.R = &serverCredentialTypeR{
			ServerCredentials: ServerCredentialSlice{o},
		}
	} else {
		related.R.ServerCredentials = append(related.R.ServerCredentials, o)
	}

	return nil
}

// SetServer of the serverCredential to the related item.
// Sets o.R.Server to related.
// Adds o to related.R.ServerCredentials.
func (o *ServerCredential) SetServer(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Server) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"server_credentials\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"server_id"}),
		strmangle.WhereClause("\"", "\"", 2, serverCredentialPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ServerID = related.ID
	if o.R == nil {
		o.R = &serverCredentialR{
			Server: related,
		}
	} else {
		o.R.Server = related
	}

	if related.R == nil {
		related.R = &serverR{
			ServerCredentials: ServerCredentialSlice{o},
		}
	} else {
		related.R.ServerCredentials = append(related.R.ServerCredentials, o)
	}

	return nil
}

// ServerCredentials retrieves all the records using an executor.
func ServerCredentials(mods ...qm.QueryMod) serverCredentialQuery {
	mods = append(mods, qm.From("\"server_credentials\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"server_credentials\".*"})
	}

	return serverCredentialQuery{q}
}

// FindServerCredential retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindServerCredential(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*ServerCredential, error) {
	serverCredentialObj := &ServerCredential{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"server_credentials\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, serverCredentialObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from server_credentials")
	}

	if err = serverCredentialObj.doAfterSelectHooks(ctx, exec); err != nil {
		return serverCredentialObj, err
	}

	return serverCredentialObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ServerCredential) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no server_credentials provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(serverCredentialColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	serverCredentialInsertCacheMut.RLock()
	cache, cached := serverCredentialInsertCache[key]
	serverCredentialInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			serverCredentialAllColumns,
			serverCredentialColumnsWithDefault,
			serverCredentialColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(serverCredentialType, serverCredentialMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(serverCredentialType, serverCredentialMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"server_credentials\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"server_credentials\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into server_credentials")
	}

	if !cached {
		serverCredentialInsertCacheMut.Lock()
		serverCredentialInsertCache[key] = cache
		serverCredentialInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ServerCredential.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ServerCredential) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	serverCredentialUpdateCacheMut.RLock()
	cache, cached := serverCredentialUpdateCache[key]
	serverCredentialUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			serverCredentialAllColumns,
			serverCredentialPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update server_credentials, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"server_credentials\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, serverCredentialPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(serverCredentialType, serverCredentialMapping, append(wl, serverCredentialPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update server_credentials row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for server_credentials")
	}

	if !cached {
		serverCredentialUpdateCacheMut.Lock()
		serverCredentialUpdateCache[key] = cache
		serverCredentialUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q serverCredentialQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for server_credentials")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for server_credentials")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ServerCredentialSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), serverCredentialPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"server_credentials\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, serverCredentialPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in serverCredential slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all serverCredential")
	}
	return rowsAff, nil
}

// Delete deletes a single ServerCredential record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ServerCredential) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ServerCredential provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), serverCredentialPrimaryKeyMapping)
	sql := "DELETE FROM \"server_credentials\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from server_credentials")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for server_credentials")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q serverCredentialQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no serverCredentialQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from server_credentials")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for server_credentials")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ServerCredentialSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(serverCredentialBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), serverCredentialPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"server_credentials\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, serverCredentialPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from serverCredential slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for server_credentials")
	}

	if len(serverCredentialAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ServerCredential) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindServerCredential(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ServerCredentialSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ServerCredentialSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), serverCredentialPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"server_credentials\".* FROM \"server_credentials\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, serverCredentialPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ServerCredentialSlice")
	}

	*o = slice

	return nil
}

// ServerCredentialExists checks if the ServerCredential row exists.
func ServerCredentialExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"server_credentials\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if server_credentials exists")
	}

	return exists, nil
}

// Exists checks if the ServerCredential row exists.
func (o *ServerCredential) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ServerCredentialExists(ctx, exec, o.ID)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ServerCredential) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no server_credentials provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(serverCredentialColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	serverCredentialUpsertCacheMut.RLock()
	cache, cached := serverCredentialUpsertCache[key]
	serverCredentialUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			serverCredentialAllColumns,
			serverCredentialColumnsWithDefault,
			serverCredentialColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			serverCredentialAllColumns,
			serverCredentialPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert server_credentials, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(serverCredentialPrimaryKeyColumns))
			copy(conflict, serverCredentialPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryCockroachDB(dialect, "\"server_credentials\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(serverCredentialType, serverCredentialMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(serverCredentialType, serverCredentialMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		_, _ = fmt.Fprintln(boil.DebugWriter, cache.query)
		_, _ = fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // CockcorachDB doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert server_credentials")
	}

	if !cached {
		serverCredentialUpsertCacheMut.Lock()
		serverCredentialUpsertCache[key] = cache
		serverCredentialUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
