kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-service: serverservice
  name: serverservice
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    k8s-service: serverservice
